---
title: "sparkvis"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**sparkvis** adds the necessary methods to **ggvis** to allow it to handle **sparklyr's** *tbl_spark* class data sets.  

Currently implemented **layers**:

- layer_boxplot

- layer_histograms

### Installation

You can install **sparkvis** from GitHub

```{r, eval = FALSE}
devtools::install_github("edgararuiz/sparkvis")
```

### Load needed libraries


```{r, eval = FALSE}
library(sparklyr)
library(ggvis)
library(sparkvis)
library(nycflights13)
```

```{r, include = FALSE, eval = TRUE}
library(sparklyr)
library(ggvis)
library(sparkvis)
library(nycflights13)
```

### Create a new Spark connection

```{r}
conf <- spark_config()
conf$`sparklyr.shell.driver-memory` <- "8G"
sc <- spark_connect(master="local", config = conf, version = "2.1.0")
```

### Copying 'flights' to the Spark environment


```{r}
spark_flights <- copy_to(sc, flights)
```

## Box Plot

```{r}
spark_flights %>% 
  ggvis(~carrier,  ~distance) %>% 
  layer_boxplots()
```

```{r}
spark_flights %>% 
  ggvis(~carrier,  ~arr_delay) %>% 
  layer_boxplots()
```

## Histogram


```{r}
spark_flights %>% 
  dplyr::filter(distance > 0) %>%
  ggvis(~distance) %>% 
  layer_histograms( stack = FALSE, width = 300) 
```

```{r}
spark_flights %>% 
  dplyr::filter(arr_delay < 200) %>%
  ggvis(~arr_delay) %>% 
  layer_histograms( stack = FALSE, width = 20) 
```



### Closing connection

```{r}
spark_disconnect(sc)
```
